#include <DHT.h>

#define DHTPIN 7
#define DHTTYPE DHT22

DHT dht(DHTPIN, DHTTYPE);

const int ledVerde = 2;
const int ledRojo = 4;
const int ledAmarillo = 3;

void setup() {
  Serial.begin(9600);

  pinMode(ledVerde, OUTPUT);
  pinMode(ledRojo, OUTPUT);
  pinMode(ledAmarillo, OUTPUT);

  dht.begin();
}

void loop() {
  float temp = dht.readTemperature();
  float hum = dht.readHumidity();

  if (!isnan(temp) && !isnan(hum)) {
    // 🔥 Enviar datos
    Serial.print("TEMP:");
    Serial.print(temp);
    Serial.print(",HUM:");
    Serial.println(hum);
  }

  // 🔥 Recibir comandos desde Raspberry
  if (Serial.available()) {
    String cmd = Serial.readStringUntil('\n');
    cmd.trim();

    if (cmd == "ROJO") {
      digitalWrite(ledRojo, HIGH);
      digitalWrite(ledVerde, LOW);
      digitalWrite(ledAmarillo, LOW);
    }
    else if (cmd == "VERDE") {
      digitalWrite(ledVerde, HIGH);
      digitalWrite(ledRojo, LOW);
      digitalWrite(ledAmarillo, LOW);
    }
    else if (cmd == "AMARILLO") {
      digitalWrite(ledAmarillo, HIGH);
      digitalWrite(ledRojo, LOW);
      digitalWrite(ledVerde, LOW);
    }
  }

  delay(500); // no RT (correcto según el taller)
}
